# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlicuotaIVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=3, max_digits=5, verbose_name=b'Porcentaje')),
            ],
            options={
                'verbose_name': 'Al\xc3\xadcuota de IVA',
                'verbose_name_plural': 'Al\xc3\xadcuotas de IVA',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name=b'Descripci\xc3\x83\xc2\xb3n')),
                ('medida', models.CharField(blank=True, max_length=60, null=True, verbose_name='Medida/Caracteristica')),
                ('nro_orden', models.CharField(blank=True, max_length=3, null=True, verbose_name=b'Ordenaci\xc3\x83\xc2\xb3n')),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'M\xc3\x83\xc2\xa1rgen')),
                ('usar_pv', models.BooleanField(default=False, verbose_name=b'Emplear Precio de venta manual')),
                ('venta', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name=b'Precio de venta')),
                ('ubicacion', models.CharField(blank=True, max_length=25, null=True, verbose_name=b'Ubicaci\xc3\x83\xc2\xb3n')),
                ('unidad_venta', models.CharField(choices=[(b'UN', b'Unidad'), (b'KG', b'Kilogramo'), (b'CJ', b'Caja'), (b'LT', b'Litro'), (b'BL', b'Blister'), (b'MT', b'Metro'), (b'BS', b'Bolsa')], default=b'UN', max_length=2, null=True, verbose_name=b'Modo de venta')),
                ('cantidad_por_bulto', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name=b'Cantidad por bulto/caja')),
                ('codigo_barras', models.CharField(blank=True, max_length=160, null=True, verbose_name='C\xc3\xb3digo de Barras')),
                ('codigo_propio', models.CharField(blank=True, max_length=160, null=True, verbose_name='C\xc3\xb3digo Propio')),
                ('cvmoneda', models.BooleanField(default=True, help_text=b'Adapta el precio a la moneda local seg\xc3\x83\xc2\xban la cotizaci\xc3\x83\xc2\xb3n', verbose_name=b'Convertir moneda')),
                ('informacion', models.TextField(blank=True, null=True)),
                ('en_oferta', models.BooleanField(default=False, verbose_name='Art\xc3\xadculo en oferta')),
                ('texto_oferta', models.TextField(blank=True, null=True)),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.AlicuotaIVA')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre de moneda')),
                ('cotiza_a_ref', models.FloatField(default=1, verbose_name='Cotizaci\xc3\xb3n a moneda de referencia')),
                ('simbolo', models.CharField(max_length=4, verbose_name='S\xc3\xadmbolo de moneda')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=b'True', verbose_name=b'Nombre de Familia')),
                ('markup', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'M\xc3\x83\xc2\xa1rgen')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('codigo', models.CharField(max_length=100, verbose_name='C\xc3\xb3digo del grupo')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_predeterminada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Articulo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_del_grupo', to='facturacion.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=b'True', verbose_name=b'Marca')),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'M\xc3\x83\xc2\xa1rgen')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioPorProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=3, help_text=b'Introduzca el precio sin iva', max_digits=9, verbose_name=b'Precio de costo')),
                ('codigo_interno', models.CharField(blank=True, help_text='El c\xc3\xb3digo en la lista del proveedor', max_length=40, null=True, verbose_name='C\xc3\xb3digo en lista')),
                ('referencia', models.BooleanField(default=False, verbose_name=b'Tomar como referencia')),
                ('ultimacompra', models.BooleanField(default=False, help_text='Indique si le compr\xc3\xb3 la \xc3\xbaltima vez a este proveedor', verbose_name='\xc3\xbaltima compra')),
                ('razon_ultimacompra', models.CharField(blank=True, help_text='Si desea aclarar por qu\xc3\xa9 decidi\xc3\xb3 comprar la ultima vez a este proveedor', max_length=40, null=True, verbose_name='Raz\xc3\xb3n por la que compr\xc3\xb3 a este proveedor')),
                ('ultima_actualizacion', models.DateField(auto_now=True, verbose_name='\xc3\x9altima actualizaci\xc3\xb3n de este registro')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppp_articulo', to='facturacion.Articulo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Cotizacion', verbose_name=b'Moneda')),
            ],
            options={
                'ordering': ('-precio',),
                'verbose_name': 'Precio por Proveedor',
                'verbose_name_plural': 'Precios por Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Raz\xc3\xb3n Social')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Tel/Fax')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cuentas', models.TextField(blank=True, null=True)),
                ('viajante', models.TextField(blank=True, null=True, verbose_name=b'Datos del viajante/Contacto')),
                ('descuento_a_lista', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'Descuento aplicado al precio de lista (%)')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=b'True', verbose_name=b'Nombre de Rubro')),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=b'M\xc3\x83\xc2\xa1rgen')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Familia')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='precioporproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Proveedor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Marca'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.Rubro'),
        ),
        migrations.AlterUniqueTogether(
            name='precioporproveedor',
            unique_together=set([('articulo', 'proveedor', 'referencia')]),
        ),
    ]
