# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_de_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsientoDebeDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_contables.AsientoContable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_cuentas.CuentaNivel3')),
            ],
        ),
        migrations.CreateModel(
            name='AsientoHaberDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros_contables.AsientoContable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_cuentas.CuentaNivel3')),
            ],
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='debe',
            field=models.ManyToManyField(null=True, related_name='CuentasDebe', through='libros_contables.AsientoDebeDetalle', to='plan_de_cuentas.CuentaNivel3'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='haber',
            field=models.ManyToManyField(null=True, related_name='CuentasHaber', through='libros_contables.AsientoHaberDetalle', to='plan_de_cuentas.CuentaNivel3'),
        ),
    ]
