# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaNivel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaNivel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_cuentas.CuentaNivel1')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaNivel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo_de_iva', models.CharField(choices=[('c', 'Cinco'), ('d', 'Diez'), ('e', 'Exenta'), ('n', 'No aplicable')], default='n', max_length=1)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_cuentas.CuentaNivel2')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('tipo_de_saldo', models.CharField(choices=[('d', 'Debe'), ('h', 'Haber')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='cuentanivel1',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_cuentas.TipoCuenta'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentanivel3',
            unique_together=set([('nombre', 'tipo')]),
        ),
        migrations.AlterUniqueTogether(
            name='cuentanivel2',
            unique_together=set([('nombre', 'tipo')]),
        ),
        migrations.AlterUniqueTogether(
            name='cuentanivel1',
            unique_together=set([('nombre', 'tipo')]),
        ),
    ]
