# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros_contables', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_comprobante', models.CharField(max_length=15)),
                ('tipo_comprobante', models.CharField(choices=[('f', 'Factura'), ('r', 'Recibo'), ('a', 'Autofactura')], max_length=1)),
                ('asiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libros_contables.AsientoContable')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together=set([('proveedor', 'numero_comprobante')]),
        ),
    ]
