# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aportantes', '0001_initial'),
        ('libros_contables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_factura', models.CharField(max_length=15, unique=True)),
                ('tipo_comprobante', models.CharField(choices=[('f', 'Factura'), ('r', 'Recibo')], max_length=1)),
                ('aportante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aportantes.Aportante')),
                ('asiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libros_contables.AsientoContable')),
            ],
        ),
    ]
